config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
    root "categories#index"

  resources :categories do
    resources :tasks
  end


  # tasks routes

  # get '/categories/:category_id/tasks', to: "tasks#index", as: "category_tasks"
  # post '/categories/:category_id/tasks', to: "tasks#create"
  # get '/categories/:category_id/tasks/new', to: "tasks#new", as: 'new_category_task'
  # get '/categories/:category_id/tasks/:id/edit', to: "tasks#edit", as: 'edit_category_task'
  # get '/categories/:category_id/tasks/:id', to: "tasks#show", as: 'category_task'
  # patch '/categories/:category_id/tasks/:id', to: "tasks#update"
  # delete '/categories/:category_id/tasks/:id', to: "tasks#destroy"

  # categories routes

  # get '/categories', to: "categories#index", as: 'categories'
  # post '/categories', to: "categories#create"
  # get '/categories/new', to: "categories#new", as: 'new_category'
  # get '/categories/:id/edit', to: "categories#edit", as: 'edit_category'
  # get '/categories/:id', to: "categories#show", as: 'category'
  # patch  '/categories/:id', to: "categories#update"
  # delete '/categories/:id', to: 'categories#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5}

  has_many :tasks, dependent: :destroy
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true, length: {minimum: 5}, uniqueness: true
  validates :date, presence: true
  belongs_to :category
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = Category.where(user_id: current_user.id) if user_signed_in?
    @tasks_today = Task.where("date >= ? and date < ? and user_id = ?", Date.today, Date.today.tomorrow, current_user.id)
  end
  
  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @category_tasks = @category.tasks.all
  end
  
  def create
    category = Category.new(category_params)
    category.update(user_id: current_user.id)

    if category.save
      redirect_to "/categories/#{category.id}", notice: "Category has been created"
    else 
      redirect_to "/categories/#{category.id}", alert: "Name #{category.errors.first.message}"
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    category = Category.find(params[:id])

    if category.update(category_params)
      redirect_to "/categories/#{category.id}"
    else 
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy

    redirect_to root_path
  end

  private

  def category_params
    params.require(:category).permit(:name, :user_id)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :get_category

  def new
    @task = @category.tasks.build
  end

  def show
    @task = Task.find(params[:id])
    # @task = Task.where(user_id: current_user.id)
  end

  def create
    task = @category.tasks.create(task_params)
    task.update(user_id: current_user.id)

    if task.save
      redirect_to category_path(@category), notice: "Task has been successfully create"
    else
      redirect_to category_path(@category), alert: "#{task.errors.first.message}"
    end
  end

  def edit
    @task = @category.tasks.find(params[:id])
  end

  def update
    task = @category.tasks.find(params[:id])

    if task.update(task_params)
      redirect_to category_path(@category)
    else 
      render :edit
    end
  end

  def destroy
    task = Task.find(params[:id])
    task.destroy

    redirect_to category_path(@category)
  end

  private

  def get_category
    @category = Category.find(params[:category_id])
  end

  def task_params
    params.require(:task).permit(:name, :description, :category_id, :date, :user_id, :done)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <div>
    <%= form.label :name %>
    <br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form', category: @category %>

<%= link_to "Back", category_path %>

app/views/categories/index.html.erb
<header class="text-right mr-8">
  <p class="mt-2">User: <%= current_user.email %></p>
  <p> <%= button_to "Sign-out", destroy_user_session_path, method: :delete, class: "border border-black rounded-xl w-24 mt-2" %> </p>
</header>

<main>
  <div class="text-center text-2xl">
    <%= Date.today.strftime("%b %d, %Y") %>
    <p>Task for today:</p>
  </div>
  <div class="border-2 mt-2 h-72 overflow-y-auto">
    
    <div class="grid grid-cols-5 overflow-y-auto">
      <% @tasks_today.each do |task| %>
        <div class="border border-black rounded-xl w-48 ml-4 mt-4 text-center py-2">
          <h3>Task: <%= task.name %></h3>
          <p>
            <span>
              <% if task.done %>
                <p> Status: Done </p>
              <% elsif %>
                <p> Status: On-going </p>
              <% end %>
            </span>
          </p>
        </div>
      <% end %>
    </div>
  </div>

  <p class="border border-black rounded-xl w-32 text-center mt-4"> <%= link_to "New Category", new_category_path %> </p>

  <p class="text-center text-2xl">Categories:</p>
  <div class="border-4 rounded-xl mt-4 pt-4 w-5/6 h-96 ml-auto mr-auto overflow-y-auto">
    <div class="grid grid-cols-4">
      <% @categories.each do |category| %>
        <div class="border border-black rounded-xl w-48 ml-4 mt-2 text-center py-2">
          <p class="mb-2"> <%= link_to category.name.titleize, category_path(category) %> </p>
          <%= link_to "View", category_path(category), class: "border border-black rounded-xl px-2" %>
          <%= link_to "Delete", category_path(category), data: {
              turbo_method: :delete,
              turbo_confirm: "Are you sure?"
            },
            class: "border border-black rounded-xl px-2"
          %>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/categories/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', categories_path(@category) %>

app/views/categories/show.html.erb
<p class="mt-2">
  <%= link_to "Home", categories_path, class: "ml-4 border border-black rounded-xl px-2" %>
</p>
<div class="flex ml-2 mt-4">
  <h1 class="border-b-2 border-black"> "<%= @category.name.titleize %>"</h1>
  <%= link_to " - Edit", edit_category_path %>
</div>

<br>
<br>
<%#= link_to "New Task", category_tasks_path(@category) %>
<%= link_to "New Task", new_category_task_path(@category), class: "ml-2 border border-black rounded-xl px-2" %>

<div>
  <% @category_tasks.each do |task| %>
    <h2>Task: <%= task.name %> </h2>
    <%= link_to "View", category_task_path(@category.id, task.id) %>
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JournalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-notebook bg-cover bg-no-repeat">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with model: [@category, @task] do |form| %>
  <p>
    <%= form.label :name %> 
    <%= form.text_area :name %>
  </p>

  <p>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </p>

  <div>
    <%= form.label :date %>
    <%= form.datetime_field :date %>
  </div>

  <p>
    <%= form.submit %>  
  </p>

<% end %>

app/views/tasks/edit.html.erb
<%= render 'form' %>

<%= link_to 'Back', category_path(@category) %>

app/views/tasks/new.html.erb
<%= render 'form'%>
<%= link_to 'Back', category_path(@category) %>

app/views/tasks/show.html.erb
<div>
  <%= form_with model: [@category, @task] do |f|  %>
    <h1> <span> <%= f.check_box :done, onchange: "this.form.submit();" %></span> Task: <%= @task.name.titleize %></h1>
    <p>Description: <%= @task.description.titleize %></p>
    <p>Date: <%= @task.date.strftime("%a - %b %-d, %Y") %> </p>
  <% end %>
</div>
<br>
<%= link_to "Back", category_path(@category)%>
<br>
<br>
<%= link_to "Edit", edit_category_task_path(@category.id, @task.id) %>
<br>
<br>
<%= link_to "Delete", category_task_path(@category, @task), data: {
    turbo_method: :delete,
    turbo_confirm: "Continue to delete"
  } 
%>